apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Moja Aplikacja — DEV</title></head>
    <body style="background-color: #fff3cd;">
      <h1>Witaj z Kustomize!</h1>
      <p>ŚRODOWISKO: <strong style="color: orange;">DEV</strong></p>
      <p>Repliki: 1 | Zasoby: minimalne</p>
    </body>
    </html>
